<?php 
function tpl_1241983612_1_2_0a5index_phtml37d5bafda0ba1486f93ca6795eba473f( $tpl, $ctx ) {
$_thistpl = $tpl ;
$_translator = $tpl->getTranslator() ;
?><style>

    img {
        display:block;
        padding-bottom:5em;
        padding-top:3em;
    }

    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }

</style>
<center>
    <div id="welcome">
        <br/>
        <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>
        <h3>This is your project's main page</h3>
        <div id="more-information">
            <img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png"/>
            Helpful Links: <br/>
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://">PHPTAL Website</a>
        </div>
    </div>
</center><?php 
}

 ?><?php /* 
*** DO NOT EDIT THIS FILE ***

Generated by PHPTAL from C:\Users\user\www\myzend\application\views\scripts\index\index.phtml (edit that file instead) */; ?>